/**
 * Execution tests: run each skill's real entrypoint and confirm its real output.
 *
 * `skills-harness.test.mjs` asks a model what a skill says. This file ignores the
 * model entirely and runs the scripts — the engine, the inspectors, the exporters,
 * the verifiers, the M injector — against workbooks generated by the suite's own
 * fixture generator, then asserts on the bytes that come back.
 *
 * Two things make these tests worth having rather than merely green:
 *
 *   1. Negative controls. Every verifier is fed a deliberately corrupted file as
 *      well as an honest one. A verifier that cannot fail proves nothing, so each
 *      one has to reject the planted bug and name it.
 *   2. Cross-implementation checks. The bash suite and the Python suite share no
 *      code, so each reading back the other's output is the strongest available
 *      evidence that either is right.
 *
 * The bug the whole suite is built around: a `Removed` row is labelled with the
 * month the removal was OBSERVED in, but carries the values from the month BEFORE
 * it — the last month the row actually existed. Get it backwards and you still get
 * a plausible-looking file.
 */

import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { after, before, describe, it } from 'node:test';

import {
  GOLDEN_ROWS,
  GOLDEN_TABLE,
  NO_PYTHON,
  PQ_QUERY,
  PQ_TEMPLATE,
  PYTHON,
  SYS_PYTHON,
  makeFixtures,
  mashupPrefix,
  py,
  readXlsx,
  readXlsxShape,
  run,
  script,
  tamperCell,
  xldiff,
  xldiffSh,
  zipParts,
} from './helpers/exec.mjs';

let fx;

before(() => {
  // Fail loudly rather than skipping: a silently-skipped execution suite is
  // indistinguishable from a passing one, which is the trap this file exists to avoid.
  assert.ok(PYTHON, NO_PYTHON);
  fx = makeFixtures();
});

after(() => fx?.cleanup());

// ---------------------------------------------------------------------------
// py-xlsx-diff-commons — the engine every other py- skill calls
// ---------------------------------------------------------------------------

describe('py-xlsx-diff-commons: the engine', () => {
  it('make_fixtures.py generates the four documented workbooks', () => {
    for (const f of ['sample.xlsx', 'sheets.xlsx', 'gap.xlsx', 'messy.xlsx']) {
      assert.ok(fs.existsSync(path.join(fx.dir, f)), `${f} was not generated`);
    }
  });

  it('renders the golden table for sample.xlsx, byte for byte', () => {
    const r = xldiff([fx.sample]);
    assert.equal(r.code, 0, r.stderr);
    assert.equal(r.stdout.trimEnd(), GOLDEN_TABLE);
  });

  it('a Removed row carries the PREVIOUS month\'s values, not the current one\'s', () => {
    const rows = JSON.parse(xldiff([fx.sample, '-f', 'json']).stdout);
    const bob = rows.find((r) => r.Month === 'Mar' && String(r.ID) === '102');

    // Bob: Active in Jan, Inactive in Feb, gone in Mar.
    assert.equal(bob.Change_Status, 'Removed');
    assert.equal(bob.Status, 'Inactive', 'Removed row must carry Feb (last seen), not Jan');
    assert.equal(bob.Owner, 'Bob', 'Removed row must carry values, not blanks');
  });

  it('emits exactly the golden change set and nothing else', () => {
    const rows = JSON.parse(xldiff([fx.sample, '-f', 'json']).stdout);
    const actual = rows.map((r) => [r.Month, r.ID, r.Change_Status, r.Status, r.Owner]);
    assert.deepEqual(actual, GOLDEN_ROWS);
  });

  it('a gap in the month sequence yields an EMPTY diff, not an error', () => {
    // gap.xlsx is Jan + Mar with no Feb. Mar's immediate predecessor is missing, so
    // Mar is a base month too, and the whole diff is empty. Exit 0 — surprising, legal.
    const r = xldiff([fx.gap, '-f', 'json']);
    assert.equal(r.code, 0, 'an empty diff is not a failure');
    assert.deepEqual(JSON.parse(r.stdout), []);
  });

  it('Modified is opt-in: absent by default, present with --detect-modified', () => {
    const off = JSON.parse(xldiff([fx.sample, '-f', 'json']).stdout);
    assert.equal(off.filter((r) => r.Change_Status === 'Modified').length, 0);

    const on = JSON.parse(xldiff([fx.sample, '-f', 'json', '--detect-modified']).stdout);
    const modified = on.filter((r) => r.Change_Status === 'Modified');
    assert.deepEqual(
      modified.map((r) => [r.Month, String(r.ID)]),
      [['Feb', '102'], ['Mar', '104']],
    );
  });

  it('--all adds Base Month and Unchanged rows, which are dropped by default', () => {
    const statuses = new Set(
      JSON.parse(xldiff([fx.sample, '-f', 'json', '--all']).stdout).map((r) => r.Change_Status),
    );
    assert.ok(statuses.has('Base Month'), 'Jan is the base month');
    assert.ok(statuses.has('Unchanged'));
  });

  it('messy.xlsx: last duplicate key wins, null keys are excluded, columns union', () => {
    const rows = JSON.parse(xldiff([fx.messy, '-f', 'json']).stdout);

    // Duplicate key 202: the LAST row wins, matching a join's last-write semantics.
    const dup = rows.find((r) => String(r.ID) === '202');
    assert.equal(dup.Status, 'Duplicate');
    assert.equal(dup.Owner, 'Bob II');

    // A null key is not a joinable row, so it never reaches the diff.
    assert.ok(rows.every((r) => r.ID !== null && r.ID !== ''), 'null-key row must not appear');

    // Region exists in only one month; it still appears, blank where absent.
    assert.ok('Region' in rows[0], 'the column union must include one-month-only columns');
  });

  it('a missing key column is a clean error: exit 1, "xldiff:" on stderr, no traceback', () => {
    const r = xldiff([fx.sample, '-k', 'NOPE']);
    assert.equal(r.code, 1);
    assert.match(r.stderr, /^xldiff: /m);
    assert.match(r.stderr, /Key column 'NOPE' is missing/);
    assert.doesNotMatch(r.stderr, /Traceback/, 'errors are reported, not raised');
  });
});

// ---------------------------------------------------------------------------
// py-xlsx-workbook-inspect — the pre-flight check
// ---------------------------------------------------------------------------

describe('py-xlsx-workbook-inspect: pre-flight', () => {
  const inspect = (args) => run(PYTHON, [script('py-xlsx-workbook-inspect', 'inspect_workbook.py'), ...args]);

  it('reports a diffable workbook as named-tables, exit 0', () => {
    const r = inspect([fx.sample]);
    assert.equal(r.code, 0, r.stderr);
    assert.match(r.stdout, /layout\s*:\s*named-tables/);
    assert.match(r.stdout, /months\s*:\s*Jan, Feb, Mar/);
    assert.match(r.stdout, /OK: diffable \(3 month\(s\) found\)/);
  });

  it('falls back to the sheets layout when no named table matches', () => {
    assert.match(inspect([fx.sheets]).stdout, /layout\s*:\s*sheets/);
  });

  it('warns that a month-sequence gap silently suppresses changes', () => {
    // The single most valuable line this skill prints: it explains an empty diff
    // that would otherwise look like a bug in the engine.
    const r = inspect([fx.gap]);
    assert.equal(r.code, 0, 'a gap is legal-but-surprising, not fatal');
    assert.match(r.stdout, /warn\s+Mar: predecessor Feb is absent/);
    assert.match(r.stdout, /base month and contributes no changes/);
  });

  it('exits 1 and names the offending months when the key column is missing', () => {
    const r = inspect([fx.sample, '-k', 'NOPE']);
    assert.equal(r.code, 1);
    for (const m of ['Jan', 'Feb', 'Mar']) {
      assert.match(r.stdout + r.stderr, new RegExp(`ERROR ${m}: key column 'NOPE' is missing`));
    }
  });

  it('--json emits a machine-readable report a pipeline can gate on', () => {
    const r = inspect([fx.gap, '--json']);
    const report = JSON.parse(r.stdout);

    assert.equal(report.layout, 'named-tables');
    assert.deepEqual(report.months_found, ['Jan', 'Mar']);
    assert.deepEqual(report.table_names, ['tbl_Jan', 'tbl_Mar']);

    // Per-month detail is what a pipeline actually gates on.
    assert.equal(report.months.Jan.has_key, true);
    assert.equal(report.months.Jan.rows, 4);
    assert.equal(report.months.Jan.source, 'table tbl_Jan');
  });

  it('--json surfaces the hazards that silently distort a diff', () => {
    const report = JSON.parse(inspect([fx.messy, '--json']).stdout);
    const hazards = Object.values(report.months);

    assert.ok(
      hazards.some((m) => m.duplicate_keys.length > 0),
      'messy.xlsx has a duplicate key, and a duplicate silently drops a row',
    );
    assert.ok(
      hazards.some((m) => m.null_keys > 0),
      'messy.xlsx has a null key, and a null key is not joinable',
    );
  });
});

// ---------------------------------------------------------------------------
// py-xlsx-diff-export — the output half (no scripts of its own; drives the engine)
// ---------------------------------------------------------------------------

describe('py-xlsx-diff-export: output formats', () => {
  it('writes a styled .xlsx: sheet Changes, frozen orange header, tbl_Changes', () => {
    const out = fx.out('py_changes.xlsx');
    assert.equal(xldiff([fx.sample, '-o', out]).code, 0);

    const shape = readXlsxShape(out);
    assert.deepEqual(shape.sheets, ['Changes']);
    assert.deepEqual(shape.tables, ['tbl_Changes'], 'output must be re-readable as input');
    assert.equal(shape.freeze, 'A2');
    assert.match(shape.header_fill, /ED7D31$/);
    assert.equal(shape.header_bold, true);
  });

  it('fill-codes rows by status: Added green, Removed red', () => {
    const out = fx.out('fills.xlsx');
    xldiff([fx.sample, '-o', out]);
    const shape = readXlsxShape(out);

    // Golden order: Removed, Added, Removed, Added.
    const expected = ['FCE4E4', 'E2EFDA', 'FCE4E4', 'E2EFDA'];
    assert.deepEqual(shape.fills.map((f) => f.slice(-6)), expected);
  });

  it('the emitted .xlsx carries the golden rows', () => {
    const out = fx.out('rows.xlsx');
    xldiff([fx.sample, '-o', out]);
    const [header, ...rows] = readXlsx(out);
    assert.deepEqual(header, ['Month', 'ID', 'Change_Status', 'Status', 'Owner']);
    assert.deepEqual(rows, GOLDEN_ROWS);
  });

  it('infers the format from the output extension', () => {
    const j = fx.out('changes.json');
    const c = fx.out('changes.csv');
    xldiff([fx.sample, '-o', j]);
    xldiff([fx.sample, '-o', c]);

    assert.deepEqual(
      JSON.parse(fs.readFileSync(j, 'utf8')).map((r) => r.Change_Status),
      ['Removed', 'Added', 'Removed', 'Added'],
    );
    const csv = fs.readFileSync(c, 'utf8');
    assert.match(csv.split(/\r?\n/)[0], /^Month,ID,Change_Status,Status,Owner$/);
  });

  it('with -o, data goes to the file and the summary to stderr — stdout stays pipeable', () => {
    const out = fx.out('quiet.xlsx');
    const r = xldiff([fx.sample, '-o', out]);
    assert.equal(r.stdout, '', 'stdout must stay clean for piping');
    assert.match(r.stderr, /xldiff: 4 changed row\(s\)/);
  });

  it('an empty diff still produces a workbook that opens (autofilter, not a table)', () => {
    // An Excel Table needs at least one data row, so a zero-change run must fall back
    // rather than emit an invalid workbook.
    const out = fx.out('empty.xlsx');
    assert.equal(xldiff([fx.gap, '-o', out]).code, 0);

    const shape = readXlsxShape(out);
    assert.deepEqual(shape.tables, [], 'no tbl_Changes when there are no data rows');
    assert.ok(shape.autofilter, 'falls back to an autofilter over the header');
    assert.equal(shape.rows.length, 1, 'header only');
  });
});

// ---------------------------------------------------------------------------
// py-xlsx-diff-verify — and the negative control that gives it meaning
// ---------------------------------------------------------------------------

describe('py-xlsx-diff-verify: proving a diff file is honest', () => {
  const verify = (args) => run(PYTHON, [script('py-xlsx-diff-verify', 'verify_diff.py'), ...args]);

  it('PASSes a changes file that really describes its source', () => {
    const out = fx.out('honest.xlsx');
    xldiff([fx.sample, '-o', out]);

    const r = verify([fx.sample, out]);
    assert.equal(r.code, 0, r.stdout + r.stderr);
    assert.match(r.stdout, /^PASS/m);
  });

  it('REJECTS a Removed row carrying the wrong month\'s values — the bug the suite exists for', () => {
    const honest = fx.out('honest2.xlsx');
    xldiff([fx.sample, '-o', honest]);

    // Plant the classic bug: Bob's Mar/Removed row gets Jan's "Active" instead of
    // Feb's "Inactive". The file still looks entirely plausible.
    const bad = tamperCell(honest, fx.out('tampered.xlsx'), {
      key: '102',
      status: 'Removed',
      col: 'Status',
      value: 'Active',
    });

    const r = verify([fx.sample, bad]);
    assert.equal(r.code, 1, 'a plausible-but-wrong file must not pass');

    const said = r.stdout + r.stderr;
    assert.match(said, /^FAIL/m);
    // The INVARIANT pass is the one that names the actual rule, having re-derived the
    // claim from the source workbook without going through the engine.
    assert.match(
      said,
      /Mar\/102: Removed row carries Status='Active', but Feb \(the month it was last seen in\) says 'Inactive'/,
    );
  });

  it('REJECTS a changes file produced from a different workbook', () => {
    const wrong = fx.out('from_messy.xlsx');
    xldiff([fx.messy, '-o', wrong]);

    const r = verify([fx.sample, wrong]);
    assert.equal(r.code, 1, 'parity must catch a wrong-workbook file');
  });
});

// ---------------------------------------------------------------------------
// py-xlsx-month-diff — the end-to-end entry point (orchestrates the others)
// ---------------------------------------------------------------------------

describe('py-xlsx-month-diff: the documented end-to-end workflow', () => {
  it('inspect -> diff -> verify: all three exit 0 and the file is the golden', () => {
    const out = fx.out('e2e.xlsx');

    const inspected = run(PYTHON, [script('py-xlsx-workbook-inspect', 'inspect_workbook.py'), fx.sample]);
    assert.equal(inspected.code, 0, 'pre-flight');

    const diffed = xldiff([fx.sample, '-o', out]);
    assert.equal(diffed.code, 0, 'diff');

    const verified = run(PYTHON, [script('py-xlsx-diff-verify', 'verify_diff.py'), fx.sample, out]);
    assert.equal(verified.code, 0, 'verify');

    const [, ...rows] = readXlsx(out);
    assert.deepEqual(rows, GOLDEN_ROWS);
  });

  it('the emitted changes file is a real named table — but is NOT itself re-diffable', () => {
    // py-xlsx-diff-export/SKILL.md claims: "because the output is a *named table*, the
    // changes file satisfies the suite's own input contract. You can diff a diff."
    //
    // Half of that holds. The output IS registered as a real Excel Table, which is the
    // property Power Query needs (Excel.CurrentWorkbook() sees named tables and nothing
    // else). But the table is named `tbl_Changes`, and the reader resolves months by
    // looking for `tbl_Jan`..`tbl_Dec` — so a changes file has no month tables at all and
    // comes back as `layout: none`. "You can diff a diff" is not true as written.
    //
    // This test pins the behaviour that actually exists, so the docs can be corrected
    // against it rather than the other way round.
    const out = fx.out('rediff_in.xlsx');
    xldiff([fx.sample, '-o', out]);

    assert.deepEqual(readXlsxShape(out).tables, ['tbl_Changes'], 'it is a named table');

    const again = run(PYTHON, [script('py-xlsx-workbook-inspect', 'inspect_workbook.py'), out, '-k', 'ID']);
    assert.equal(again.code, 1, 'a changes file is not a month workbook');
    assert.match(again.stdout, /layout\s*:\s*none/);
    assert.match(again.stdout, /ERROR No month tables/);
  });
});

// ---------------------------------------------------------------------------
// py-powerquery-m-diff-inject — the Excel-native path
// ---------------------------------------------------------------------------

describe('py-powerquery-m-diff-inject: rewriting the embedded M', () => {
  const inject = (args, python = SYS_PYTHON) =>
    run(python, [script('py-powerquery-m-diff-inject', 'inject_m.py'), ...args]);

  before(function () {
    if (!fs.existsSync(PQ_TEMPLATE)) this.skip(`no Power Query template at ${PQ_TEMPLATE}`);
  });

  it('--print-m extracts the M buried four layers deep in the workbook', () => {
    // customXml (UTF-16) -> base64 -> length-prefixed blob -> nested ZIP -> Formulas/Section1.m
    const r = inject([PQ_TEMPLATE, '--print-m']);
    assert.equal(r.code, 0, r.stderr);
    assert.match(r.stdout, /Excel\.CurrentWorkbook\(\)/, 'that is M, not a ZIP header');
  });

  it('runs on the standard library alone — openpyxl is not needed and must not be used', () => {
    const stdlibOnly = run(SYS_PYTHON, ['-c', 'import openpyxl']).code !== 0;
    const r = inject([PQ_TEMPLATE, '--print-m'], SYS_PYTHON);
    assert.equal(r.code, 0, 'the injector must work without openpyxl installed');
    if (!stdlibOnly) {
      // openpyxl happens to be importable here; the claim is still that it is unused.
      assert.doesNotMatch(
        fs.readFileSync(script('py-powerquery-m-diff-inject', 'inject_m.py'), 'utf8'),
        /^\s*import openpyxl|^\s*from openpyxl/m,
        'inject_m.py must not import openpyxl — it would destroy the query',
      );
    }
  });

  it('injects new M and the code survives the round-trip out of the new file', () => {
    const out = fx.out('injected.xlsx');
    const r = inject([PQ_TEMPLATE, '--m-code', PQ_QUERY, '-o', out]);
    assert.equal(r.code, 0, r.stderr);
    assert.match(r.stderr + r.stdout, /M verified/, 'the script re-reads what it wrote');

    const back = inject([out, '--print-m']).stdout;
    const wanted = fs.readFileSync(PQ_QUERY, 'utf8');
    assert.equal(back.trimEnd(), wanted.trimEnd(), 'the M that landed must be the M we sent');
  });

  it('recomputes the length prefix, so the blob it writes is not corrupt', () => {
    // The 4 bytes before the package declare its length. Rewriting Section1.m changes the
    // package's size, so copying that prefix forward yields a blob whose declared length
    // disagrees with reality — and Excel reports a corrupt file.
    //
    // This does not overlap with the round-trip test above. inject_m.py's own read-back
    // slices the package BY the declared length and only checks the slice starts with "PK",
    // so a prefix that overshoots quietly swallows trailer bytes, still parses, and still
    // prints "M verified". Copying the stale prefix forward produced a file that declared
    // 2562 bytes for a 2040-byte package — 522 bytes of slack — and the script called it
    // verified. Excel would not. Only this check fails on that file.
    const out = fx.out('prefix.xlsx');
    const r = inject([PQ_TEMPLATE, '--m-code', PQ_QUERY, '-o', out]);
    assert.equal(r.code, 0, r.stderr);

    const { declared, zipEndsAt, slack } = mashupPrefix(out);
    assert.notEqual(zipEndsAt, -1, 'the declared package must not be a truncated ZIP');
    assert.equal(
      slack,
      0,
      `the length prefix must exactly describe the package: declared ${declared}, ZIP ends at ${zipEndsAt}`,
    );
  });

  it('preserves every other part of the workbook, so nothing else can be disturbed', () => {
    const out = fx.out('injected2.xlsx');
    inject([PQ_TEMPLATE, '--m-code', PQ_QUERY, '-o', out]);

    const before = zipParts(PQ_TEMPLATE);
    const after = zipParts(out);
    assert.deepEqual(after, before, 'the part list must be unchanged');
    assert.ok(before.some((p) => p.startsWith('customXml/')), 'the query part is there to begin with');
  });

  it('the openpyxl trap is real: a bare load/save silently deletes the entire query', () => {
    // This is why the injector copies the ZIP by hand. It is measured, not theoretical —
    // and it is why "edit with openpyxl, then inject into customXml/" cannot work: by the
    // time you look, openpyxl has already deleted the directory you were going to inject into.
    const wrecked = fx.out('openpyxl_roundtrip.xlsx');
    py(
      ['import sys,openpyxl', 'openpyxl.load_workbook(sys.argv[1]).save(sys.argv[2])'].join('\n'),
      [PQ_TEMPLATE, wrecked],
    );

    const before = zipParts(PQ_TEMPLATE).filter((p) => p.startsWith('customXml/'));
    const after = zipParts(wrecked).filter((p) => p.startsWith('customXml/'));
    assert.ok(before.length > 0, 'the template has a query');
    assert.equal(after.length, 0, 'openpyxl dropped every customXml part — the query is gone');
  });
});

// ---------------------------------------------------------------------------
// bash-xlsx-diff-commons — the shell engine (no Python, no openpyxl)
// ---------------------------------------------------------------------------

describe('bash-xlsx-diff-commons: the shell engine', () => {
  it('renders the same golden table as the Python engine', () => {
    const r = xldiffSh([fx.sample]);
    assert.equal(r.code, 0, r.stderr);
    assert.equal(r.stdout.trimEnd(), GOLDEN_TABLE);
  });

  it('gets the Removed-row rule right in shell too', () => {
    const rows = JSON.parse(xldiffSh([fx.sample, '-f', 'json']).stdout);
    const bob = rows.find((r) => r.Month === 'Mar' && String(r.ID) === '102');
    assert.equal(bob.Change_Status, 'Removed');
    assert.equal(bob.Status, 'Inactive');
  });

  it('xlsx2tsv.sh resolves the layout, the sheet list, and a single month', () => {
    const tsv = (args) => run('bash', [script('bash-xlsx-diff-commons', 'xlsx2tsv.sh'), ...args]);

    assert.equal(tsv([fx.sample, '--layout']).stdout.trim(), 'named-tables');
    assert.equal(tsv([fx.sheets, '--layout']).stdout.trim(), 'sheets');

    const jan = tsv([fx.sample, '--month', 'Jan']).stdout.trim().split('\n');
    assert.equal(jan[0], 'ID\tStatus\tOwner', 'header row of tbl_Jan');
    assert.equal(jan.length, 5, 'header + 4 data rows');
  });

  it('an empty diff and a missing key behave as they do in Python', () => {
    assert.deepEqual(JSON.parse(xldiffSh([fx.gap, '-f', 'json']).stdout), []);
    assert.equal(xldiffSh([fx.sample, '-k', 'NOPE']).code, 1);
  });

  it('an EMPTY diff exits 0 in every format — a zero-change run is not a failure', () => {
    // Regression. `table`, `csv` and `json` used to end their brace group with
    //     [ -n "$ROWS" ] && printf '%s\n' "$ROWS"
    // whose test returns 1 when there are no rows. As the last command in the group that
    // became the group's status, `pipefail` propagated it, and `set -e` killed the script
    // with exit 1 — one line before its own intentional `exit 0`. stdout was still correct,
    // which is exactly why a stdout-only parity check never caught it: any CI job running
    // the bash suite would fail a legitimate zero-change month.
    for (const format of ['table', 'csv', 'json', 'tsv']) {
      const r = xldiffSh([fx.gap, '-f', format]);
      assert.equal(r.code, 0, `-f ${format} on an empty diff must exit 0, said: ${r.stderr}`);
    }
  });
});

// ---------------------------------------------------------------------------
// bash-xlsx-workbook-inspect
// ---------------------------------------------------------------------------

describe('bash-xlsx-workbook-inspect: pre-flight, shell only', () => {
  const inspect = (args) => run('bash', [script('bash-xlsx-workbook-inspect', 'inspect.sh'), ...args]);

  it('reports a diffable workbook, exit 0', () => {
    const r = inspect([fx.sample]);
    assert.equal(r.code, 0, r.stderr);
    assert.match(r.stdout, /layout\s*:\s*named-tables/);
    assert.match(r.stdout, /OK: diffable \(3 month\(s\) found\)/);
  });

  it('exits 1 when the key column is missing', () => {
    assert.equal(inspect([fx.sample, '-k', 'NOPE']).code, 1);
  });
});

// ---------------------------------------------------------------------------
// bash-xlsx-diff-export — building a real .xlsx with zip and heredocs
// ---------------------------------------------------------------------------

describe('bash-xlsx-diff-export: writing .xlsx from shell', () => {
  it('writes a workbook that openpyxl — which shares no code with it — can read', () => {
    const out = fx.out('sh_changes.xlsx');
    const tsv = xldiffSh([fx.sample, '-f', 'tsv']);
    assert.equal(tsv.code, 0);

    const w = run('bash', [script('bash-xlsx-diff-export', 'write_xlsx.sh'), out], { input: tsv.stdout });
    assert.equal(w.code, 0, w.stderr);

    const shape = readXlsxShape(out);
    assert.deepEqual(shape.sheets, ['Changes']);
    assert.deepEqual(shape.tables, ['tbl_Changes'], 'registered as a real Excel Table');
    assert.equal(shape.freeze, 'A2');

    const [header, ...rows] = shape.rows;
    assert.deepEqual(header, ['Month', 'ID', 'Change_Status', 'Status', 'Owner']);
    assert.deepEqual(rows, GOLDEN_ROWS);
  });
});

// ---------------------------------------------------------------------------
// bash-xlsx-diff-verify — with the same negative control
// ---------------------------------------------------------------------------

describe('bash-xlsx-diff-verify: proving a diff file is honest, shell only', () => {
  const verify = (args) => run('bash', [script('bash-xlsx-diff-verify', 'verify.sh'), ...args]);

  it('PASSes an honest changes file', () => {
    const out = fx.out('sh_honest.xlsx');
    xldiff([fx.sample, '-o', out]);

    const r = verify([fx.sample, out]);
    assert.equal(r.code, 0, r.stdout + r.stderr);
    assert.match(r.stdout, /^PASS/m);
  });

  it('REJECTS the planted Removed-row bug and names the rule', () => {
    const honest = fx.out('sh_honest2.xlsx');
    xldiff([fx.sample, '-o', honest]);
    const bad = tamperCell(honest, fx.out('sh_tampered.xlsx'), {
      key: '102',
      status: 'Removed',
      col: 'Status',
      value: 'Active',
    });

    const r = verify([fx.sample, bad]);
    assert.equal(r.code, 1, 'a plausible-but-wrong file must not pass the shell verifier either');
    assert.match(
      r.stdout + r.stderr,
      /Mar\/102: Removed row carries Status='Active', but Feb \(the month it was last seen in\) says 'Inactive'/,
    );
  });
});

// ---------------------------------------------------------------------------
// bash-xlsx-month-diff — the end-to-end shell entry point
// ---------------------------------------------------------------------------

describe('bash-xlsx-month-diff: end-to-end with no Python at all', () => {
  it('inspect -> diff -> write -> verify, entirely in shell', () => {
    const out = fx.out('sh_e2e.xlsx');

    assert.equal(run('bash', [script('bash-xlsx-workbook-inspect', 'inspect.sh'), fx.sample]).code, 0);

    const tsv = xldiffSh([fx.sample, '-f', 'tsv']);
    assert.equal(tsv.code, 0);

    const w = run('bash', [script('bash-xlsx-diff-export', 'write_xlsx.sh'), out], { input: tsv.stdout });
    assert.equal(w.code, 0, w.stderr);

    const v = run('bash', [script('bash-xlsx-diff-verify', 'verify.sh'), fx.sample, out]);
    assert.equal(v.code, 0, v.stdout + v.stderr);

    const [, ...rows] = readXlsx(out);
    assert.deepEqual(rows, GOLDEN_ROWS);
  });
});

// ---------------------------------------------------------------------------
// Cross-implementation parity — the strongest check available
// ---------------------------------------------------------------------------

describe('parity: the bash suite and the Python suite agree', () => {
  for (const fixture of ['sample', 'sheets', 'gap', 'messy']) {
    for (const format of ['table', 'json']) {
      it(`${fixture}.xlsx as ${format}: byte-identical across both engines`, () => {
        const book = fx[fixture];
        const p = xldiff([book, '-f', format]);
        const s = xldiffSh([book, '-f', format]);
        assert.equal(p.code, 0, p.stderr);
        assert.equal(s.code, 0, s.stderr);
        assert.equal(s.stdout, p.stdout);

        // Exit codes are part of the contract too. PARITY.md compared stdout only, and an
        // exit-code divergence on the empty diff hid behind byte-identical output for
        // exactly that reason — a caller running `set -e` would have seen it before we did.
        assert.equal(s.code, p.code, 'the two engines must agree on the exit code, not just the bytes');
      });
    }
  }

  it('an .xlsx written by BASH passes the PYTHON verifier', () => {
    const out = fx.out('x_sh.xlsx');
    const tsv = xldiffSh([fx.sample, '-f', 'tsv']);
    run('bash', [script('bash-xlsx-diff-export', 'write_xlsx.sh'), out], { input: tsv.stdout });

    const r = run(PYTHON, [script('py-xlsx-diff-verify', 'verify_diff.py'), fx.sample, out]);
    assert.equal(r.code, 0, r.stdout + r.stderr);
  });

  it('an .xlsx written by PYTHON passes the BASH verifier', () => {
    const out = fx.out('x_py.xlsx');
    xldiff([fx.sample, '-o', out]);

    const r = run('bash', [script('bash-xlsx-diff-verify', 'verify.sh'), fx.sample, out]);
    assert.equal(r.code, 0, r.stdout + r.stderr);
  });
});
